version: '3.8'

name: ${FRONTEND_COMPOSE_NAME}
services:
  nginx:
    container_name: frontend-nginx
    build:
      context: ../
      dockerfile: ./docker-deploy/Dockerfile
      args:
        - NGINX_RELEASE
        - NODE_RELEASE
    environment:
      - DOMAIN_URL=${DOMAIN_URL}
      - API_PORT=${API_PORT}
    volumes:
      - ./dist:/usr/share/nginx/html:rw
      - ./nginx/locations:/etc/nginx/include_servers:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
      - "${API_PORT}:${API_PORT}"
    restart: unless-stopped

  nginx-certbot:
    container_name: nginx-certbot
    image: nginx:${NGINX_RELEASE}
    volumes:
      - ./nginx/nginx_certbot.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
    ports:
      - "80:80"
    restart: no

  # To generate certs:
  # docker compose run --rm  certbot certonly --webroot --webroot-path /var/www/certbot/ -d legends.bmstu.ru
  # To renew certs:
  # docker compose run --rm certbot renew
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx-certbot
