name: Makefile CI

on:
  push:
    branches: [ "master" ]
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Deploy to server
      if: ${{ !env.ACT }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.DEPLOY_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_DEPLOY_KEY }}
        script: |
          cd ${{ vars.PROJECT_PATH }}
          sudo make update
