name: Makefile CI

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.DEPLOY_HOST }}
        username: legend
        key: ${{ secrets.SSH_DEPLOY_KEY }}
        script: |
          cd /home/vue-frontend-template
          sudo make update
