name: Makefile CI

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
    - uses: actions/checkout@v3

    - name: env
      run: touch docker-deploy/.env

    - name: build
      run: make build
